apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: spaceshield
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hamalouispaceend-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: MYSQL_USERNAME
          value: "root"
        - name: MYSQL_PASSWORD
          value: "youssef"
        - name: MYSQL_DATABASE
          value: "spaceshielddb"
        - name: SPACE_TRACK_USERNAME
          value: "professionelproaw201@gmail.com"
        - name: SPACE_TRACK_PASSWORD
          value: "Password123456789"
        - name: OREKIT_PATH
          value: "/app/orekit-data"
        volumeMounts:
        - name: orekit-data
          mountPath: /app/orekit-data
          readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 240
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: orekit-data
        persistentVolumeClaim:
          claimName: orekit-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: spaceshield
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP