version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-container
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: spring-backend
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./orekit-data-main:/app/orekit-data
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: vite-frontend
    depends_on:
      - backend
    ports:
      - "3001:3000"
    networks:
      - app-network
    restart: unless-stopped

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8088:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql-data:
  jenkins_home:

networks:
  app-network:
    driver: bridge
