version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-container
    restart: always
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: spring-backend
    depends_on:
      - mysql
    env_file:
      - ./backend/.env
    ports:
      - "8081:8081"
    volumes:
      #Mount the Orekit data folder correctly for Windows
      - /c/Users/USER/Desktop/orekit-data-main:/app/orekit-data
    restart: unless-stopped

volumes:
  mysql-data:
