apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spaceshield-backend
  namespace: spaceshield
  labels:
    app: backend
    release: spaceshield-monitoring
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: management
    path: /actuator/prometheus
    interval: 30s
---
# Service to expose backend monitoring port
apiVersion: v1
kind: Service
metadata:
  name: backend-monitoring
  namespace: spaceshield
  labels:
    app: backend
spec:
  ports:
  - name: management
    port: 8081
    targetPort: 8081
  selector:
    app: backend