apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: spaceshield
  labels:
    app: backend
    tier: api
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
        tier: api
    spec:
      containers:
      - name: backend
        image: hamalouispaceend-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        # Database Configuration
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3316"
        - name: MYSQL_USERNAME
          value: "root"
        - name: MYSQL_PASSWORD
          value: "youssef"
        - name: MYSQL_DATABASE
          value: "spaceshielddb"
        
        # Space Track API Configuration
        - name: SPACE_TRACK_USERNAME
          value: "professionelproaw201@gmail.com"
        - name: SPACE_TRACK_PASSWORD
          value: "Password123456789"
        
        # Orekit Configuration
        - name: OREKIT_PATH
          value: "/app/orekit-data"
        
        volumeMounts:
        - name: orekit-data
          mountPath: /app/orekit-data
          readOnly: true
        
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
      
      volumes:
      - name: orekit-data
        persistentVolumeClaim:
          claimName: orekit-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: spaceshield
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: spaceshield
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70