apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spaceshield-backend
  namespace: spaceshield
  labels:
    app: backend
    release: spaceshield-monitoring
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
---
# Update service to use port 8080 for monitoring
apiVersion: v1
kind: Service
metadata:
  name: backend-monitoring
  namespace: spaceshield
  labels:
    app: backend
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: backend