nameOverride: "spaceshield-monitoring"

prometheus:
  service:
    type: NodePort
    # Remove nodePort line - Kubernetes will auto-assign

grafana:
  enabled: true
  adminPassword: "spaceshield123"
  service:
    type: NodePort
    # Remove nodePort line - Kubernetes will auto-assign

alertmanager:
  service:
    type: NodePort
    # Remove nodePort line - Kubernetes will auto-assign

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true