apiVersion: v1
kind: PersistentVolume
metadata:
  name: orekit-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /host_mnt/c/Users/lenovo/OneDrive/Bureau/GL_Projects/orekit-data-mai
    type: Directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orekit-data-pvc
  namespace: spaceshield
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: orekit-data-pv